---
title: "Installation"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Installation}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

In the following the [pre-required software](#pre-required-software) and the 
workflow for installing the [R package aquanes.report](#r-package-installation) 
is described.


## Pre-required software


- [R (>= 3.3.2)](https://cloud.r-project.org/): for the development of the R 
package **aquanes.report** R 3.3.2 was used. However, also later R releases (e.g. 3.4) should be working.  

- [Rtools](https://cran.rstudio.com/bin/windows/Rtools/): required to compile R packages from source. The required version depends on the installed R version. 

- [Pandoc](http://pandoc.org/installing.html): is required to convert the reports 
from plain text format (markdown) into the different formats (docx, html, pdf). 
We used

- [Miktex](https://miktex.org/download): needs to be installed in case that **pdf** reports should be created.


For the advanced user it is further recommended to install the latest version of 
the integrated development environment (IDE) [RStudio Desktop "open source licence"](https://www.rstudio.com/products/rstudio/download2/#download). 


## R package installation

Once all [pre-required software](#pre-required-software) is installed on your operating system you can proceed with the R package installation workflow as described below.


### Step 1) Installation of R package "devtools" 

The R package "devtools" is required for downloading and installing the R package "aquanes.report" from Github. 
For installing it execute the following lines of code in R(Studio):
```r
if (!require("devtools")) {
  install.packages("devtools", repos = "https://cloud.r-project.org")
}
```

### Step 2) Installation of R package "aquanes.report"
#### 2.1) Specific release 

In case you want to install a specific release you need to specify the 
parameter "ref", which needs to be set to a valid release (check here: [releases](https://github.com/KWB-R/aquanes.report/releases)) by running the following code in R(Studio). This tutorial at least requires release version [v.0.2.0-alpha](https://github.com/KWB-R/aquanes.report/releases/tag/v.0.2.0-alpha)):
```r
devtools::install_github("kwb-r/aquanes.report", 
                         ref = "v.0.2.0-alpha",
                         dependencies = TRUE)
```

#### 2.2) Development version

If you want to install the latest (possibly unstable!) development version, 
execute the following lines of code in R(Studio):

```r
devtools::install_github("kwb-r/aquanes.report", 
                         dependencies = TRUE)
```

### Step 3) Check the installation folder of the package in R(Studio) with:
```r
system.file(package = "aquanes.report")
``` 

### Step 4) Two files need to be copied:

#### 4.1) mySQL configuration file ('.my.cnf')

The '.my.cnf' file is required to establish a connection to the mySQL database 
for querying the operational data for the Haridwar site. It needs to be copied into the following directory:
```r
system.file("shiny/haridwar", package = "aquanes.report")
``` 
#### 4.2) Analytics spreadsheet file ('analytics.xlsx')

The 'analytics.xlsx' file contains the analytics data for the Haridwar site and 
needs to be copied into the following directory:

```r
system.file("shiny/haridwar/data", package = "aquanes.report")
```

